### ISSUE TITLE
Get rid of compiler warnings due to unused code in floyd_warshall.rs

### ISSUE THREAD

**Issue by easbar** [easbar/fast_paths#1]
The code in floyd_warshall.rs is only used in tests at the moment.

**Comment by Eh2406** [comment]
Then you can add `#[cfg(test)]` to only compile it when running tests.

**Comment by easbar** [comment]
Where exactly do I need to put `#[cfg(test)]` ? Did you try it ?

**Comment by Eh2406** [comment]
I will give it a try if it works I'll make a PR.
