### ISSUE TITLE
Possible perf regression with Rust 1.45

### ISSUE THREAD

**Issue by dabreegster** [easbar/fast_paths#20]
I just switched to a new [Rust](https://blog.rust-lang.org/2020/07/16/Rust-1.45.0.html) and building the CH is suddenly stalling out. I'll dig in soon and see what's going on.

**Comment by easbar** [comment]
Ok thanks! Let me know if I can help with anything.

**Comment by dabreegster** [comment]
Just recording debugging here, no help needed yet.

1.45.0: when queue is 7000: contracted node 10380 / 17380, num edges fwd: 29136, num edges bwd: 30631, neighbors 4

1.43.0: when queue is 7000: contracted node 10380 / 17380, num edges fwd: 10466, num edges bwd: 11642, neighbors 0

number of edges is 3x higher

**Comment by dabreegster** [comment]
1.44.0 is same as 1.43.0, fast and fine. The break is 44->45.

"Out of range float to int conversions using as has been defined as a saturating conversion. This was previously undefined behaviour, but you can use the {f64, f32}::to_int_unchecked methods to continue using the current behaviour, which may be desirable in rare performance sensitive situations."

This feels like the problem. `run_contraction` casts a priority to a usize Weight. Looking into this.

**Comment by dabreegster** [comment]
https://github.com/easbar/fast_paths/blob/cfb19807c0dae0b6a5034d62959a6bd2abe45079/src/fast_graph_builder.rs#L82 is the problem, it casts a negative f32 to usize. That now does something different.

I have an easy fix working, using std::cmp::Reverse for the priority queue. Cleaning up, PR soon
