### ISSUE TITLE
Copy and Clone Traits

### ISSUE THREAD

**Issue by Alfred-Mountfield** [easbar/fast_paths#25]
Just wondering why the structs like `FastGraph` don't derive `Clone`? 
It's blocking structs that own one from deriving those traits.

**Comment by easbar** [comment]
The only reason is probably nobody needed this so far. Feel free to send a pull request for this.

**Comment by Alfred-Mountfield** [comment]
Makes sense, I've made the PR at #26, not familiar with the project though so let me know if it's nonsensical.

**Comment by easbar** [comment]
Fixed in #26
