### ISSUE TITLE
Possibly wrong path?

### ISSUE THREAD

**Issue by auryn31** [easbar/fast_paths#38]
Hey, i am using this lib for the current advent of code. 
And I got the wrong result for my input. The test input is working and everything else also. Maybe you can verify that the code is working correctly from your point of view?

I got the result of `3019` but it should be `3012`. I rerun the code multiple times and also verified, that the enlarged matrix is correct (it is :/). So I cannot find any issues in my code. My next thought is, that your lib maybe has an issue? :D

Maybe you want/can take a look :)

You can find the code here:
https://github.com/auryn31/aoc_2021/blob/main/day_15/src/main.rs

But there is a solid chance my code is wrong :D

Best

**Comment by NotNorom** [comment]
@auryn31 have you figured out if it really was a problem of this library?

**Comment by auryn31** [comment]
@NotNorom Sorry, totally forgot about that. And not it is so long ago. I have no idea anymore. Would have to dig into that :/

**Comment by NotNorom** [comment]
No worries, it's been a while after all :laughing:
