### ISSUE TITLE
format of datasets such as New York

### ISSUE THREAD

**Issue by zhumingpassional** [easbar/fast_paths#40]
In a table, it shows the consumed time, such as New York. 
But where is the dataset? is the format shapefile? 
could you pls provide more details?

**Comment by easbar** [comment]
There is a link to the dataset above the table, but apparently it wasn't working (anymore?). I just updated it, please let me know if it works for you.

**Comment by zhumingpassional** [comment]
@easbar 
yes. it works now. thanks for your work.

Does it support other formats such as shapefile or OSM? Or to support them, how to do?

**Comment by easbar** [comment]
No, the data import is only implemented for the DIMACS format (see [here](https://github.com/easbar/fast_paths/blob/df54f4950880157d22ae8e5a58fe83dab80193bb/src/input_graph.rs#L253)). But doing something similar for shapefiles should be fairly easy.

**Comment by zhumingpassional** [comment]
thanks for your help.

**Comment by zhumingpassional** [comment]
In DIMACS, we only know the index of nodes. If we know the longitude latitude of a node, how to know the corresponding node index  in DIMACS? 
I will appreciate it if you can share the experience. thanks again.

**Comment by easbar** [comment]
I'm not sure I understand the question, but DIMACS offers a coordinate file (*.co) that has the coordinates for each node: http://www.diag.uniroma1.it/~challenge9/format.shtml#coord 

The fast_paths library makes no use of these coordinates, though.
