### ISSUE TITLE
method calc_path_multiple_sources_and_targets not found in `PathCalculator`

### ISSUE THREAD

**Issue by zhumingpassional** [easbar/fast_paths#41]
I test the following , it raise error: let shortest_path = path_calculator.calc_path_multiple_sources_and_targets(&fast_graph, sources, targets); ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ method not found in `PathCalculator`

// ... see above
// we want to either start at node 2 or 3 both of which carry a different initial weight
let sources = vec![(3, 5), (2, 7)];
// ... and go to either node 6 or 8 which also both carry a cost upon arrival
let targets = vec![(6, 2), (8, 10)];
// calculate the path with minimum cost that connects any of the sources with any of the targets while taking into 
// account the initial weights of each source and node
let shortest_path = path_calculator.calc_path_multiple_sources_and_targets(&fast_graph, sources, targets);

**Comment by easbar** [comment]
What exactly are you trying to do?

**Comment by zhumingpassional** [comment]
Calculating paths between multiple sources and targets

the above code is copied from the homepage.

**Comment by easbar** [comment]
Ok, I see. You are probably using the `0.2.0` release which does not include the changes that were made since then. I will prepare the ~~`0.3.0`~~ `1.0.0` version then, which will include `calc_path_multiple_sources_and_targets`. In the meantime you can of course build the code yourself using the code from the master branch.

**Comment by easbar** [comment]
I just released version 1.0.0 on crates.io, please let me know if this is working so we can close here.

**Comment by zhumingpassional** [comment]
it works now. thanks
