### ISSUE TITLE
The dijkstra's implementation should be bidirectional

### ISSUE THREAD

**Issue by PayasR** [easbar/fast_paths#7]
There are still some perf gains to be had if we switch to a bidirectional dijkstra's implementation for the query phase. 
(See https://arxiv.org/pdf/1504.05140.pdf , pages 22-23)

**Comment by easbar** [comment]
The query algorithm already is bidirectional, see [here](https://github.com/easbar/fast_paths/blob/master/src/path_calculator.rs). IMO the easiest way to improve query speed at the moment would be to implement stall on demand, something like [this](https://github.com/graphhopper/graphhopper/blob/b6ebc9b9e09a8865e1e8f9109f710e0b68baecc6/core/src/main/java/com/graphhopper/routing/DijkstraBidirectionCH.java#L61).

**Comment by PayasR** [comment]
Oh okay, I was looking at [this](https://github.com/easbar/fast_paths/blob/master/src/dijkstra.rs) instead. Yes, stalling is needed too.. do you have it on the To-Do list? I don't see any project roadmap available on GitHub..
