### ISSUE TITLE
Huge performance difference in terms of running time

### ISSUE THREAD

**Issue by ChenZhongPu** [easbar/fast_paths#9]
I use the `USA-road-d.COL` road network, which contains 435666 nodes and  1042400 edges. 

Generally, it costs more than 61300 micros, and **it is much slower than you reported benchmark**.

## Data
I download the dataset from [dataset](http://users.diag.uniroma1.it/challenge9/download.shtml ) and then clean it (remove duplicated edges; remove loop...).

The cleaned data can be download from [google drive](https://drive.google.com/file/d/1U1gR7IBO7d8EMyvP0gFMuELLFSGuY7al/view?usp=sharing)

> USA-road-d.COL 435666 1042400
> 0 1 14567
> 0 46 7059
> 1 0 14567
> 1 30 16448
> ...

## Experiment hardware
I run the experiments on a Windows desktop with i7 8700 CPU, 16 GB memory.

## Code of running queries of CH
The saved CH file is 80.1MB.

```
    let fast_graph = fast_paths::load_from_disk("fast_graph_col.fp").unwrap();
    let start = Instant::now();
    let shortest_path = fast_paths::calc_path(&fast_graph, s, t);
    let duration = start.elapsed();
    println!("Time elapsed in ch_run() is: {:?}", duration.as_micros());
```
The average query time to answer the shortest from `0` to `1001` is `61303` micros.

**Comment by easbar** [comment]
You need to re-use the path calculator object, see the https://github.com/easbar/fast_paths#batch-wise-shortest-path-calculation section in readme.
